# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

compiler: gcc

os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        - MAIN_CMD='python setup.py'
        - CONDA_CHANNELS='http://ssb.stsci.edu/astroconda'
        - CONDA_DEPENDENCIES='pytest=3.6'
        - PIP_DEPENDENCIES=''
        - PYTHON_VERSION=3.6
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - EVENT_TYPE='push pull_request'

    matrix:
        - SETUP_CMD='install'
        - SETUP_CMD='test'
#        - PYTHON_VERSION=2.7 SETUP_CMD='test'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        # build sphinx documentation with warnings
        - os: linux
          env: SETUP_CMD='build_sphinx'
               CONDA_DEPENDENCIES=$CONDA_DEPENDENCIES
               PIP_DEPENDENCIES='sphinx_rtd_theme stsci_rtd_theme sphinx-automodapi'

        # PEP8 check with flake8 (only once, i.e. "os: linux")
        - os: linux
          env: MAIN_CMD='flake8 --count'
               SETUP_CMD='mirage'

    allow_failures:
        # PEP8 will fail for numerous reasons. Ignore it.
        - env: MAIN_CMD='flake8 --count'
               SETUP_CMD='mirage'

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - $MAIN_CMD $SETUP_CMD
