name: mirage-py3.8

channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python==3.8.13
- pip:
    - asdf==2.13.0
    - astropy==5.1.1
    - astroquery==0.4.6
    - batman-package==2.4.9
    - bokeh==2.4.3
    - crds==11.16.16
    - grismconf==1.32
    - hotsoss==0.1.7
    - h5py==3.7.0
    - ipython==8.6.0
    - jupyter==1.0.0
    - jwst==1.8.2
    - jwst-backgrounds==1.1.2
    - lxml==4.9.1
    - matplotlib==3.6.2
    - nircam_gsim==1.60
    - numpy==1.23.4
    - photutils>=1.5.0
    - pysiaf==0.18.0
    - pytest==7.2.0
    - scipy==1.9.3
    - sphinx==5.3.0
    - synphot==1.1.1
    - pyyaml==6.0
    - webbpsf==1.1.0