channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- asdf>=2.1.0
- astropy==3.2.1
- astroquery>=0.3.8
- crds>=7.4.1
- gwcs>=0.11
- healpy>=1.12.5
- h5py>=2.8.0
- ipython
- jupyter
- jwxml>=0.3.0
- lxml>=3.6.4
- matplotlib>=3.0.0
- numpy>=1.16
- photutils>=0.6
- pytest>=3.8.1
- python>=3.6,<3.7
- scipy>=1.1.0
- sphinx>=2.1
- synphot>=0.2.0
- webbpsf>=0.9.0
- pyyaml>=5.1.2
- pip:
    - jwst-backgrounds>=1.1.1
    - pysiaf>=0.6.1
    - git+https://github.com/spacetelescope/jwst@0.14.2
    - git+https://github.com/npirzkal/GRISMCONF
    - git+https://github.com/npirzkal/NIRCAM_Gsim
