name: mirage-py3.11

channels:
- http://ssb.stsci.edu/astroconda
- conda-forge
- defaults
dependencies:
- pip
- python==3.11.9
- pip:
    - asdf==3.4.0
    - astropy==6.1.3
    - astroquery==0.4.7
    - batman-package==2.4.9
    - bokeh==3.5.2
    - crds==11.18.4
    - grismconf==1.50
    - h5py==3.11.0
    - hotsoss==0.1.10
    - ipython==8.27.0
    - jupyter==1.1.1
    - jwst==1.15.1
    - jwst-backgrounds==1.3.0
    - jwst_gtvt==1.0.1
    - lxml==5.3.0
    - matplotlib==3.9.2
    - nircam_gsim>=1.71
    - numpy<2.0
    - photutils==1.13.0
    - pysiaf==0.23.3
    - pytest==8.3.3
    - pyyaml==6.0.2
    - scipy==1.14.1
    - sphinx==8.0.2
    - synphot==1.4.0
    - webbpsf==1.4.0