name: mirage_osx
channels:
  - http://ssb.stsci.edu/astroconda-dev
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py36_0
  - astroquery=0.3.8=py36_0
  - atomicwrites=1.1.5=py36_0
  - automat=0.7.0=py_1
  - beautifulsoup4=4.6.1=py36_0
  - bleach=2.1.4=py_1
  - bokeh=0.13.0=py36_0
  - certifi=2018.4.16=py36_0
  - constantly=15.1.0=py_0
  - distributed=1.22.0=py36_0
  - entrypoints=0.2.3=py36_2
  - et_xmlfile=1.0.1=py36_0
  - filelock=3.0.4=py36_0
  - healpy=1.11.0=py36_1
  - html5lib=1.0.1=py_0
  - hyperlink=17.3.1=py_0
  - idna=2.7=py36_0
  - imageio=2.3.0=py36_0
  - incremental=17.5.0=py_0
  - ipykernel=4.9.0=py36_0
  - ipython=6.5.0=py36_0
  - ipywidgets=7.4.0=py_0
  - jdcal=1.4=py_1
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jupyter_client=5.2.3=py_1
  - jupyter_core=4.4.0=py_0
  - keyring=13.2.1=py36_0
  - libgcc=4.8.5=hdbeacc1_10
  - libsodium=1.0.16=0
  - mistune=0.8.3=py36h470a237_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - networkx=2.1=py36_0
  - notebook=5.6.0=py36_1
  - olefile=0.45.1=py36_0
  - openpyxl=2.5.6=py_0
  - pandoc=2.2.2=hde52d81_1
  - pandocfilters=1.4.2=py_1
  - pexpect=4.6.0=py36_0
  - pip=10.0.1=py36_0
  - prometheus_client=0.3.0=py_0
  - ptyprocess=0.6.0=py36_0
  - pyasn1=0.4.4=py_0
  - pyasn1-modules=0.2.1=py_0
  - pyhamcrest=1.9.0=py_2
  - pyopenssl=18.0.0=py36_0
  - pytest=3.6.4=py36_0
  - pytest-runner=4.2=py_1
  - pyzmq=17.1.2=py36hae99301_0
  - requests=2.19.1=py36_0
  - send2trash=1.5.0=py_0
  - service_identity=17.0.0=py_0
  - setuptools=39.2.0=py36_0
  - six=1.11.0=py36_1
  - sortedcontainers=2.0.4=py36_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - twisted=18.7.0=py36h470a237_1
  - urllib3=1.23=py36_0
  - webencodings=0.5.1=py_1
  - wheel=0.31.1=py36_0
  - widgetsnbextension=3.4.0=py36_1
  - zeromq=4.2.5=hfc679d8_5
  - zope.interface=4.5.0=py36h470a237_1
  - appnope=0.1.0=py36hf537a9a_0
  - attrs=18.1.0=py36_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - cffi=1.11.5=py36h342bebf_0
  - chardet=3.0.4=py36_1
  - click=6.7=py36hec950be_0
  - cloudpickle=0.5.3=py36_0
  - cryptography=2.2.2=py36h1de35cc_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.28.4=py36h0a44026_0
  - cytoolz=0.9.0.1=py36h1de35cc_1
  - dask=0.18.2=py36_0
  - dask-core=0.18.2=py36_0
  - decorator=4.3.0=py36_0
  - freetype=2.9.1=hb4e5f40_0
  - h5py=2.8.0=py36h3c9e6ae_0
  - hdf5=1.10.2=hfa1e0ec_1
  - heapdict=1.0.0=py36_2
  - icu=58.2=h4b95b61_1
  - intel-openmp=2018.0.3=0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py36hb385e00_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.34=he12f830_0
  - libtiff=4.0.9=hcb84e12_1
  - libxml2=2.9.8=hab757c2_1
  - libxslt=1.1.32=hb819dd2_0
  - locket=0.2.0=py36hca03003_1
  - lxml=4.2.3=py36hef8c89e_0
  - markupsafe=1.0=py36h1de35cc_1
  - matplotlib=2.2.2=py36hbf02d85_2
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - more-itertools=4.2.0=py36_0
  - mpmath=1.0.0=py36_2
  - msgpack-python=0.5.6=py36h04f5b5a_0
  - ncurses=6.1=h0a44026_0
  - numpy=1.14.3=py36h9bb19eb_1
  - numpy-base=1.14.3=py36h479e554_1
  - openssl=1.0.2o=h26aff7b_0
  - packaging=17.1=py36_0
  - pandas=0.23.3=py36h6440ff4_0
  - parso=0.3.1=py36_0
  - partd=0.3.8=py36hf5c4cb8_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pillow=5.2.0=py36hb68e598_0
  - pluggy=0.6.0=py36_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - psutil=5.4.6=py36h1de35cc_0
  - py=1.5.4=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36h240cd3f_0
  - pyparsing=2.2.0=py36_1
  - pysocks=1.6.8=py36_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywavelets=0.5.2=py36h1d22016_2
  - pyyaml=3.13=py36h1de35cc_0
  - readline=7.0=hc1231fa_4
  - scikit-image=0.14.0=py36h0a44026_1
  - scipy=1.1.0=py36hf1f7d93_0
  - semantic_version=2.6.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sqlite=3.24.0=ha441bb4_0
  - tblib=1.3.2=py36hda67792_0
  - tk=8.6.7=h35a86e2_3
  - toolz=0.9.0=py36_0
  - tornado=5.0.2=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zict=0.1.3=py36_0
  - zlib=1.2.11=hf3cbc9b_2
  - jwxml=0.3.0=py36_1
  - poppy=0.7.0=py36_0
  - pysynphot=0.9.12=py36_0
  - webbpsf-data=0.6.0=1
  - asdf=2.0.0rc.dev61+g37d57aa=py36_2
  - astropy=4.0.0.dev10518+g0526009=py36_0
  - cfitsio=3.440=4
  - crds=7.2.5.dev3+g3bef456=py36_3
  - drizzle=1.10.dev2+gbec16a2=py36_2
  - fitsverify=4.18=5
  - freetds=1.00.9=0
  - gwcs=0.10a.dev9+g5c9f6d5=py36_2
  - jplephem=2.8.dev0+g9926bb5=py36_2
  - jwst=0.10.0.dev0+g4d1a743=py36_4
  - namedlist=1.7=py36_1
  - parsley=1.3=py36_0
  - photutils=0.4.dev308+g8de0150=py36_4
  - pymssql=2.1.3=py36_1
  - spherical-geometry=1.2.1.dev10+g9375ee8=py36_1
  - stsci.image=2.3.0.dev0+g720cb3a=py36_2
  - stsci.imagestats=1.4.2.dev0+g59e0e47=py36_0
  - stsci.stimage=0.2.2.dev0+g7049ddc=py36_0
  - stsci.tools=3.4.12.dev33+g349cb3c=py36_0
  - unixodbc=2.3.4=0
  - verhawk=0.0.2.dev2+g803ce78=py36_1
  - pip:
    - colorclass==1.2.0
    - github3.py==0.9.3
    - gnureadline==6.3.8
    - ipdb==0.8
    - jwst-backgrounds==1.1.1
    - mock==1.0.1
    - pysiaf>=0.2.0
    - terminaltables==1.2.1
    - uritemplate.py==0.3.0
    - webbpsf==0.7.0

