name: mirage_linux
channels:
  - http://ssb.stsci.edu/astroconda-dev
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - alabaster=0.7.11=py_3
  - astroquery=0.3.8=py36_0
  - babel=2.6.0=py_1
  - bleach=2.1.4=py_1
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1001
  - docutils=0.14=py36_1
  - entrypoints=0.2.3=py36_2
  - gmp=6.1.2=hfc679d8_0
  - healpy=1.12.4=py36h7127e17_0
  - html5lib=1.0.1=py_0
  - imagesize=1.1.0=py_0
  - ipykernel=5.0.0=py_0
  - ipywidgets=7.4.2=py_0
  - jeepney=0.4=py_0
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py_0
  - keyring=13.2.1=py36_0
  - libgfortran=3.0.0=1
  - libsodium=1.0.16=h470a237_1
  - mistune=0.8.3=py36h470a237_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - nbsphinx=0.3.5=py_0
  - notebook=5.7.0=py36_0
  - openssl=1.0.2p=h470a237_0
  - pandoc=2.3=0
  - pandocfilters=1.4.2=py_1
  - prometheus_client=0.3.1=py_1
  - pytest-runner=4.2=py_1
  - pyzmq=17.1.2=py36hae99301_0
  - qtconsole=4.4.1=py36_1
  - secretstorage=3.1.0=py36_0
  - send2trash=1.5.0=py_0
  - snowballstemmer=1.2.1=py_1
  - sphinx=1.8.1=py36_0
  - sphinx_rtd_theme=0.4.1=py_0
  - sphinxcontrib-websupport=1.1.0=py_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - webencodings=0.5.1=py_1
  - widgetsnbextension=3.4.2=py36_0
  - zeromq=4.2.5=hfc679d8_6
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.2.1=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - backcall=0.1.0=py36_0
  - beautifulsoup4=4.6.3=py36_0
  - blas=1.0=mkl
  - bokeh=0.13.0=py36_0
  - cffi=1.11.5=py36he75722e_1
  - chardet=3.0.4=py36_1
  - click=6.7=py36h5253387_0
  - cloudpickle=0.5.5=py36_0
  - cryptography=2.3.1=py36hc365091_0
  - cycler=0.10.0=py36_0
  - cython=0.28.5=py36hf484d3e_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=0.19.2=py36_0
  - dask-core=0.19.2=py36_0
  - dbus=1.13.2=h714fa37_1
  - decorator=4.3.0=py36_0
  - distributed=1.23.2=py36_0
  - expat=2.2.6=he6710b0_0
  - filelock=3.0.8=py36_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - hdf5=1.10.2=hba1933b_1
  - heapdict=1.0.0=py36_2
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - imageio=2.4.1=py36_0
  - intel-openmp=2019.0=118
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20170329=h6b74fdf_2
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.34=hb9fc6fc_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.9=he85c1e1_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.8=h26e45fe_1
  - libxslt=1.1.32=h1312cb7_0
  - locket=0.2.0=py36_1
  - lockfile=0.12.2=py36_0
  - lxml=4.2.5=py36hefd8a0e_0
  - markupsafe=1.0=py36h14c3975_1
  - matplotlib=3.0.0=py36h5429711_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h4414c95_1
  - mkl_random=1.0.1=py36h4414c95_1
  - more-itertools=4.3.0=py36_0
  - mpmath=1.0.0=py36_2
  - msgpack-python=0.5.6=py36h6bb024c_1
  - ncurses=6.1=hf484d3e_0
  - networkx=2.1=py36_0
  - numpy=1.14.3=py36hcd700cb_1
  - numpy-base=1.14.3=py36h9be14a7_1
  - olefile=0.46=py36_0
  - packaging=17.1=py36_0
  - pandas=0.23.4=py36h04863e7_0
  - parso=0.3.1=py36_0
  - partd=0.3.8=py36_0
  - pcre=8.42=h439df22_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.2.0=py36heded4f4_0
  - pip=10.0.1=py36_0
  - pluggy=0.7.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - psutil=5.4.7=py36h14c3975_0
  - ptyprocess=0.6.0=py36_0
  - py=1.6.0=py36_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36_1
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.6.8=py36_0
  - pytest=3.8.1=py36_0
  - pytest-arraydiff=0.2=py36h39e3cac_0
  - pytest-astropy=0.4.0=py36_0
  - pytest-doctestplus=0.1.3=py36_0
  - pytest-openfiles=0.3.0=py36_0
  - pytest-remotedata=0.3.0=py36_0
  - python=3.6.6=hc3d631a_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywavelets=1.0.0=py36hdd07704_0
  - pyyaml=3.13=py36h14c3975_0
  - qt=5.9.6=h8703b6f_2
  - readline=7.0=h7b6447c_5
  - requests=2.19.1=py36_0
  - scikit-image=0.14.0=py36hf484d3e_1
  - scikit-learn=0.20.0=py36h4989274_1
  - scipy=1.1.0=py36hd20e5f9_0
  - semantic_version=2.6.0=py36_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - sip=4.19.8=py36hf484d3e_0
  - six=1.11.0=py36_1
  - sortedcontainers=2.0.5=py36_0
  - sqlite=3.25.2=h7b6447c_0
  - tblib=1.3.2=py36h34cf8b6_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=5.1=py36h14c3975_0
  - traitlets=4.3.2=py36_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zict=0.1.3=py36_0
  - zlib=1.2.11=ha838bed_2
  - pysynphot=0.9.12=py36_0
  - webbpsf-data=0.7.0=0
  - asdf=2.1.0.dev1+ga161518=py36_2
  - astropy=4.0.0.dev10786+gd099cfe=py36_0
  - cfitsio=3.440=5
  - crds=7.2.6.dev105+ga1c1767=py36_4
  - drizzle=1.10.dev2+gbec16a2=py36_2
  - fitsverify=4.18=6
  - freetds=1.00.9=0
  - gwcs=0.10a.dev21+g75e92da=py36_2
  - jplephem=2.8.dev0+g9926bb5=py36_2
  - jwst=0.12.0a.dev115+g9d5eb8c=py36_4
  - namedlist=1.7=py36_1
  - parsley=1.3=py36_1
  - photutils=0.5.dev35+g639bd20=py36_0
  - pymssql=2.1.3=py36_1
  - spherical-geometry=1.2.1.dev11+g5b65401=py36_1
  - stsci.image=2.3.0.dev0+g720cb3a=py36_2
  - stsci.imagestats=1.5.1.dev1+g8f96637=py36_0
  - stsci.stimage=0.2.2.dev0+g7049ddc=py36_0
  - stsci.tools=3.4.13.dev0+g5f25467=py36_0
  - unixodbc=2.3.4=0
  - verhawk=0.0.3.dev0+g4f4a60c=py36_1
  - pip:
    - et-xmlfile==1.0.1
    - jdcal==1.4
    - jwst-backgrounds==1.1.1
    - jwxml==0.3.0
    - msgpack==0.5.6
    - openpyxl==2.5.8
    - poppy==0.7.0
    - pysiaf==0.2.5
    - relic==1.1.2
    - webbpsf==0.7.0

