name: mirage_osx
channels:
  - http://ssb.stsci.edu/astroconda-dev
  - conda-forge
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - astroquery=0.3.8=py36_0
  - babel=2.6.0=py_1
  - bleach=2.1.4=py_1
  - ca-certificates=2018.8.24=ha4d7672_0
  - certifi=2018.8.24=py36_1001
  - docutils=0.14=py36_1001
  - entrypoints=0.2.3=py36_1002
  - healpy=1.11.0=py36_1
  - html5lib=1.0.1=py_0
  - imagesize=1.1.0=py_0
  - ipykernel=5.0.0=pyh24bf2e0_1
  - ipywidgets=7.4.2=py_0
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py_0
  - keyring=13.2.1=py36_0
  - libsodium=1.0.16=h470a237_1
  - mistune=0.8.3=py36h470a237_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - nbsphinx=0.3.5=py_0
  - notebook=5.7.0=py36_0
  - openssl=1.0.2p=h470a237_0
  - pandoc=2.3.1=0
  - pandocfilters=1.4.2=py_1
  - prometheus_client=0.3.1=py_1
  - pyqt=5.6.0=py36h8210e8a_7
  - pytest-runner=4.2=py_1
  - pyzmq=17.1.2=py36hae99301_0
  - qt=5.6.2=h9e3eb04_4
  - qtconsole=4.4.1=py36_1
  - send2trash=1.5.0=py_0
  - sip=4.18.1=py36hfc679d8_0
  - snowballstemmer=1.2.1=py_1
  - sphinx=1.8.1=py36_0
  - sphinx_rtd_theme=0.4.1=py_0
  - sphinxcontrib-websupport=1.1.0=py_1
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - webencodings=0.5.1=py_1
  - widgetsnbextension=3.4.2=py36_0
  - zeromq=4.2.5=hfc679d8_5
  - appnope=0.1.0=py36hf537a9a_0
  - asn1crypto=0.24.0=py36_0
  - atomicwrites=1.2.1=py36_0
  - attrs=18.2.0=py36h28b3542_0
  - backcall=0.1.0=py36_0
  - beautifulsoup4=4.6.3=py36_0
  - blas=1.0=mkl
  - bokeh=0.13.0=py36_0
  - cffi=1.11.5=py36h6174b99_1
  - chardet=3.0.4=py36_1
  - click=6.7=py36hec950be_0
  - cloudpickle=0.5.6=py36_0
  - cryptography=2.3.1=py36hdbc3d79_0
  - cycler=0.10.0=py36hfc81398_0
  - cython=0.28.5=py36h0a44026_0
  - cytoolz=0.9.0.1=py36h1de35cc_1
  - dask=0.19.2=py36_0
  - dask-core=0.19.2=py36_0
  - decorator=4.3.0=py36_0
  - distributed=1.23.2=py36_0
  - filelock=3.0.8=py36_0
  - freetype=2.9.1=hb4e5f40_0
  - h5py=2.8.0=py36h878fce3_3
  - hdf5=1.10.2=hfa1e0ec_1
  - heapdict=1.0.0=py36_2
  - icu=58.2=h4b95b61_1
  - idna=2.7=py36_0
  - imageio=2.4.1=py36_0
  - intel-openmp=2019.0=118
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py36hb385e00_0
  - kiwisolver=1.0.1=py36h0a44026_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgcc=4.8.5=hdbeacc1_10
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.34=he12f830_0
  - libtiff=4.0.9=hcb84e12_2
  - libxml2=2.9.8=hab757c2_1
  - libxslt=1.1.32=hb819dd2_0
  - locket=0.2.0=py36hca03003_1
  - lockfile=0.12.2=py36_0
  - lxml=4.2.5=py36hef8c89e_0
  - markupsafe=1.0=py36h1de35cc_1
  - matplotlib=3.0.0=py36h54f8f79_0
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - more-itertools=4.3.0=py36_0
  - mpmath=1.0.0=py36_2
  - msgpack-python=0.5.6=py36h04f5b5a_1
  - ncurses=6.1=h0a44026_0
  - networkx=2.1=py36_0
  - numpy=1.14.3=py36h9bb19eb_1
  - numpy-base=1.14.3=py36h479e554_1
  - olefile=0.46=py36_0
  - packaging=17.1=py36_0
  - pandas=0.23.4=py36h6440ff4_0
  - parso=0.3.1=py36_0
  - partd=0.3.8=py36hf5c4cb8_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pillow=5.3.0=py36hb68e598_0
  - pip=10.0.1=py36_0
  - pluggy=0.7.1=py36h28b3542_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - psutil=5.4.7=py36h1de35cc_0
  - ptyprocess=0.6.0=py36_0
  - py=1.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.1=py36_0
  - pysocks=1.6.8=py36_0
  - pytest=3.8.1=py36_0
  - pytest-arraydiff=0.2=py36h39e3cac_0
  - pytest-astropy=0.4.0=py36_0
  - pytest-doctestplus=0.1.3=py36_0
  - pytest-openfiles=0.3.0=py36_0
  - pytest-remotedata=0.3.0=py36_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pywavelets=1.0.0=py36h1d22016_0
  - pyyaml=3.13=py36h1de35cc_0
  - readline=7.0=h1de35cc_5
  - requests=2.19.1=py36_0
  - scikit-image=0.14.0=py36h0a44026_1
  - scikit-learn=0.20.0=py36h4f467ca_1
  - scipy=1.1.0=py36hf1f7d93_0
  - semantic_version=2.6.0=py36_0
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.11.0=py36_1
  - sortedcontainers=2.0.5=py36_0
  - sqlite=3.25.2=ha441bb4_0
  - tblib=1.3.2=py36hda67792_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py36_0
  - tornado=5.1.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zict=0.1.3=py36_0
  - zlib=1.2.11=hf3cbc9b_2
  - pysynphot=0.9.12=py36_0
  - webbpsf-data=0.7.0=0
  - asdf=2.1.0.dev1+ga161518=py36_2
  - astropy=4.0.0.dev10818+gedd8090=py36_0
  - cfitsio=3.440=5
  - crds=7.2.6.dev143+g1c80b2c=py36_4
  - drizzle=1.10.dev2+gbec16a2=py36_2
  - fitsverify=4.18=6
  - freetds=1.00.9=0
  - gwcs=0.10a.dev25+g75a2435=py36_2
  - jplephem=2.8.dev1+gc1b4c18=py36_2
  - jwst=0.12.0a.dev134+g9fd3662=py36_4
  - namedlist=1.7=py36_1
  - parsley=1.3=py36_1
  - photutils=0.5.dev43+g1a55172=py36_0
  - pymssql=2.1.3=py36_1
  - spherical-geometry=1.2.1.dev11+g5b65401=py36_1
  - stsci.image=2.3.0.dev0+g720cb3a=py36_2
  - stsci.imagestats=1.5.3.dev0+g9f0dbc0=py36_0
  - stsci.stimage=0.2.2.dev0+g7049ddc=py36_0
  - stsci.tools=3.4.13.dev0+g5f25467=py36_0
  - unixodbc=2.3.4=0
  - verhawk=0.0.3.dev0+g4f4a60c=py36_1
  - pip:
    - et-xmlfile==1.0.1
    - jdcal==1.4
    - jwst-backgrounds==1.1.1
    - jwxml==0.3.0
    - msgpack==0.5.6
    - openpyxl==2.5.8
    - poppy==0.7.0
    - pysiaf==0.2.4
    - relic==1.1.2
    - webbpsf==0.7.0
